### ISSUE TITLE
Darklearning > text is not always visible when selected

### ISSUE THREAD

**Issue by officialbishowb** [RiedleroD/userstyles-riedler#21]
When you select a text in a course (English), the text is not visible.
![image](https://user-images.githubusercontent.com/55999477/166197392-d9678592-16c9-4db3-af19-effee2e9dbde.png)

**Comment by RiedleroD** [comment]
possibly a problem with selector specificity - I'll just do an `!important` on `color:htxt` in userselect. Should be somewhere far up in the file, but I'll have a look at it later.

**Comment by RiedleroD** [comment]
PRs are welcome!
