### ISSUE TITLE
Highlighted words in search results appear light gray on yellow

### ISSUE THREAD

**Issue by Korb** [RiedleroD/userstyles-riedler#22]
![Screenshot 2022-05-11 at 10-50-51 Bugs and Suggestions](https://user-images.githubusercontent.com/3509797/167797332-418067b5-8e65-4a2b-850e-91d8512abfff.png)

> Foreground:#EEEEEE
> Background:#FFEEB8
> The contrast ratio is: 1,0:1
> Text failed at Level AA
> Text failed at Level AAA
> Large text failed at Level AA
> Large text failed at Level AAA

Mozilla Firefox 100.0 (64-bit)
Stylus 1.5.21 (27 August 2021)
Microsoft Windows 10.0.19044.1706

**Comment by RiedleroD** [comment]
works on my end. Do you have the newest version of this style? It should be 1.0.1.

**Comment by RiedleroD** [comment]
I noticed that the style on userstyles.world still had 1.0.0 for whatever reason… I updated it manually now. Could you check if that fixed it?

**Comment by Korb** [comment]
> Could you check if that fixed it?

Yes:
![Screenshot 2022-05-16 at 00-58-01 Bugs and Suggestions](https://user-images.githubusercontent.com/3509797/168495628-a8f8823a-6c0d-4b74-82c8-2e6422eee4ea.png)
