### ISSUE TITLE
Darklearning: Dropdowns are displayed within the element and are therefore not visible

### ISSUE THREAD

**Issue by officialbishowb** [RiedleroD/userstyles-riedler#25]
Some dropdown lists (mostly the lower ones) appear within the element and are therefore not visible. Like this:
![image](https://user-images.githubusercontent.com/55999477/169688818-1fb0e0ae-08a9-4b9e-91dd-dc337452544c.png)

It should be like this:
![image](https://user-images.githubusercontent.com/55999477/169688829-51d3d749-ca9d-4543-b20e-5384c4f9dbf8.png)

**Comment by RiedleroD** [comment]
seems to have been introduced in 17dd3feb02a8d099dbcf3e48d72777463a1ab27c. I don't remember why I added this, but let's try removing line 1120 and see if something else breaks.

**Comment by RiedleroD** [comment]
feel free to try out [the development branch](https://github.com/RiedleroD/userstyles-riedler/raw/Darklearning/Darklearning.user.css) to test if anything doesn't work as expected after this change. If nothing broke, It'll be included with the next stable version, whenever that will be released.

**Comment by RiedleroD** [comment]
closing as no side-effects have been found so far. The next stable release will be released within the next hour.
